### ISSUE TITLE
Mouse cursor movement issue with 16:10 screen aspect ratio

### ISSUE THREAD

**Issue by DienoX** [sipeed/NanoKVM#484]
Hi,
It occurs mouse cursor movement issue with 16:10 screen aspect ratio.
When using KVM the mouse has an increasing or decreasing offset compared to the host cursor. In the center of the screen the rate is almost perfect. On the left and right the edge is terribly offset between the remote and physical cursor.

Please fix it. I have the latest version of nanokvm software update

**Comment by yaunz** [comment]
I have the same problem with 16:10 screen

**Comment by itsgps** [comment]
+1 for me - just started using a NanoKVM device as RDP not working on my work laptop...That is, it is, but Auth is an issue.  N E Ways - 16:10 screen - and exact same symptom.
Any thoughts on this?

**Comment by itsgps** [comment]
OK - so the issue is - on the 16:10 - you likely have a resolution like 1920 x 1200 rather than 1920 x 1080.  Thing is the NanoKVM really only likely supports standard aspect ratios.

<img width="441" height="316" alt="Image" src="https://github.com/user-attachments/assets/af94498e-db56-40de-952a-45157f16a9bb" />
As such - if you change the laptop to 1920 x 1080 it should be fine - Mine was!

**Comment by DienoX** [comment]
This thread is about not changing the resolution

**Comment by itsgps** [comment]
> This thread is about not changing the resolution

Actually it doesn't specifically say that - it just notes that it is for 16:10 aspect.  Adding the info I have may assist from a Development perspective - and/or for anyone else having the same issue to have a work around.  i.e. I am more than happy to have my screen at 1920x1080 when using the laptop from my PC - versus having to use the laptop directly - because my PC has a 49" Ultra wide and a 32" monitor attached.  So was always easier for me to RDP to laptop - which at the moment is not working.

SO for me the reset to 16:9 is a work around - but I definitely would like it fixed as I am sure anyone else seeing the thread would also like.

**Comment by JustSomeGuyNZ** [comment]
+1 for requesting a fix for this.

**Comment by Ivan-Firefly** [comment]
Same for me, 16:10 works fine for vertical axis and has offset on the edges of the screen for horizontal axis

**Comment by sirmeili** [comment]
> OK - so the issue is - on the 16:10 - you likely have a resolution like 1920 x 1200 rather than 1920 x 1080. Thing is the NanoKVM really only likely supports standard aspect ratios.
> 
> <img alt="Image" width="441" height="316" src="https://private-user-images.githubusercontent.com/41974173/486551464-af94498e-db56-40de-952a-45157f16a9bb.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM0MDAzMDgsIm5iZiI6MTc2MzQwMDAwOCwicGF0aCI6Ii80MTk3NDE3My80ODY1NTE0NjQtYWY5NDQ5OGUtZGI1Ni00MGRlLTk1MmEtNDUxNTdmMTZhOWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTE3VDE3MjAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MjI5NWZjMjBhN2FiZDlkYjZjYzY1ODI2OGQ5MzNmMTE1NDRhZTFjMzFmNjYyNjk4YjY2ZjU3ZDEzNjg4ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Znwb68bg-Wgl2U9U0jN6QdpzfVMEANPHCwWURjY2MJo"> As such - if you change the laptop to 1920 x 1080 it should be fine - Mine was!

1920x1200 is a standard resolution though and 16:10 is a standard aspect ratio for computers.


Edit: So is 1680x1050, which is the resolution of my monitor connected to my server. I have to "mirror" the displays so that I can retain local control as well as remote.

**Comment by wj-xiao** [comment]
We fixed a related issue in version [2.3.0](https://github.com/sipeed/NanoKVM/blob/main/CHANGELOG.md). Please update and see if it resolves the problem.

**Comment by sirmeili** [comment]
I am on 2.3.0 and this did not fix it for me (using 1680x1050, which is 16:10). the mouse only lines up when I'm in the exact center. Is there some setting I should use in the nanoKVM to adjust for this?

Here is a screenshot (mouse pointers are on the right hand side)

<img width="1504" height="909" alt="Image" src="https://github.com/user-attachments/assets/1d0aed79-3f48-4f5f-b99c-46a905acd180" />

**Comment by wj-xiao** [comment]
The issue is caused by an aspect ratio mismatch: the actual display is 16:10, but NanoKVM is outputting a 16:9 stream.
Since the mouse coordinates are calculated based on the 16:9 resolution, this results in mouse drift.

The key is to ensure NanoKVM outputs a 16:10 image. If you are controlling a Windows system, this requires a few extra steps:

1. Set the resolution to **Auto** in the NanoKVM web UI.
2. Manually set the **actual resolution** to 16:10 inside the remote Windows system settings.

Please refer to this [document](https://wiki.sipeed.com/hardware/en/kvm/NanoKVM_Pro/faq.html#HDMI-Icon-Lit-on-NanoKVM-Screen-but-No-Video-Displayed-in-Web-Interface) for more details.

**Comment by alexisfrjp** [comment]
Same here, on the left, no problem. But more the mouse goes to the right, more the gap increases.
Happens with Ubuntu live 24.10
