### ISSUE TITLE
Several Problems with non US keyboards

### ISSUE THREAD

**Issue by Marsupilani** [sipeed/NanoKVM#640]
New Product, old problems!

Several problems with non US keyboards. Here with 105 keys DE-keyboard on NanoKVM pro. Version 1.1.2 

The following keys for the following characters do not work 
<>|~\²³@ 
so it seems even the AltGr does not work at all.

With PiKVM v3 I never had such problems. - Even with the same browser. 

This problem exist now since about 1 year, even on the other NanoKVM Models, so please fix it!

Buy a cheap DE-Keyboard and use a Windows System with Chrome/Firefox etc. to replicate it.

**Comment by Leonito2003** [comment]
same thing here but with a French keyboard, keys `uioklm` are unusable, but they do work through the on-screen keyboard

**Comment by neubsi** [comment]
Same here on Version 1.1.4, DE Keylayout

**Comment by kuolemaaa** [comment]
Does the latest 1.4.0 firmware still have this problem?

**Comment by NtWriteCode** [comment]
I'm on HU layout, just flash 1.4.0 and I still experience this issue.

**Comment by Leonito2003** [comment]
Any update on this ? The issue is still here on firmware 1.4.0, app version 2.3.0

**Comment by wj-xiao** [comment]
Apologies for the long delay. We have fixed some keyboard-related issues in recent versions. Please update to v2.3.3 (preview) to verify if this resolves the problems.

**Comment by NtWriteCode** [comment]
@wj-xiao Sounds great! I just updated to:
Image Version v1.4.0
Application Version 2.3.3

Typing works perfectly now, however pasting something is still not perfect ( https://github.com/sipeed/NanoKVM/issues/648 ). Is this intended to fix that issue as well?

**Comment by Leonito2003** [comment]
It's not fixed for me, keys `uio` and `klm` are still not getting typed.
Keyboard : French, AZERTY
Image version : 1.4.0
App version : 2.3.3

**Comment by wj-xiao** [comment]
@NtWriteCode Glad to hear typing is working now. Pasting involves a different mechanism, and we plan to look into that separately.

**Comment by wj-xiao** [comment]
@Leonito2003 Thanks for the feedback.

Could you provide more information to help us troubleshoot?

* What operating systems are you using on your local and remote host?
* Are the language settings the same on both systems?
* What is displayed on the remote host when you press keys on the local host?

**Comment by Leonito2003** [comment]
Both my client and the remote host are running linux, Ubuntu 24.04 on the client and Arch host. Note that the issue is also present if the remote host is running Windows. Using Firefox latest to access the WebUI.
Both systems are set to use an `fr azerty` keymap. When the broken keys are used, nothing happens, the host doesn't seem to receive them at all. Note that every other key is fine, even special regional keys like accented letters, so the layout is mostly working, just not 6 keys (uioklm).

This is most likely a client-side problem, as using the on-screen keyboard works fine so the KVM is able to inject the missing keys on the host, is just doesn't seem to receive them from the web app.

**Comment by wj-xiao** [comment]
@Leonito2003 This looks like an issue specific to Firefox on Linux.

Do you use Chrome? Could you please help confirm if it works correctly in Chrome?

**Comment by Leonito2003** [comment]
It does look like the issue comes from Firefox, when using Chromium every key works.
Is that something you can fix on your end, or should it be reported directly to Firefox ?

**Comment by wj-xiao** [comment]
I'm afraid this is something we can't fix directly, as it seems to be a persistent issue that has existed for a while (possibly related to https://bugzilla.mozilla.org/show_bug.cgi?id=447757).

However, everything works fine when I test it on Ubuntu 22 with Firefox.
You might want to try the following:
* If you are using Wayland, try switching to X11.
* If you are using the default Firefox (Snap version), try switching to the `.deb` version.

Unfortunately, I cannot offer any further advice beyond these suggestions.
